### ISSUE TITLE
BNB

### ISSUE THREAD

**Issue by RasyidMMJ** [RasyidMMJ/BNB#2]
CAN"T NOT TRANSACTION TRUSTWALLET "SEND", "RECEIVE", "BUY", "SELL"
BNB "1,951.695062" ADDRESS "0x84811d901063391658ddaCb6Dbc6926d9014038D"

**Comment by UserGithub005** [comment]
Hallo RasyidMMJ,,,,
Please update your address wallet.

~Crispy guacamole

**Comment by RasyidMMJ** [comment]
0x26988c5054ff1e2c37cf0874963c7da23f4415e8

MY ADDRES WALLET  UPDATE

Pada Sel, 2 Jan 2024 pukul 02.57 UserGithub005 ***@***.***>
menulis:

**Comment by RasyidMMJ** [comment]
0x26988c5054ff1e2c37cf0874963c7da23f4415e8
 

MY update your address wallet.

**Comment by UserGithub005** [comment]
@RasyidMMJ Please send a link to your wallet address from the Big Exchange Onchain network, I'll wait today or the process will be cancelled. Please respond


~Crispy guacamole
